kind: Service
apiVersion: v1
metadata:
  name: Ballerina
  namespace: ballerina
spec:
  type: ClusterIP
  selector:
    name: Ballerina
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: Ballerina
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type"
spec:
  tls:
  - hosts:
    - Ballerina.ae.dev.us-east-1.k8s.appianci.net
  rules:
  - host: Ballerina.ae.dev.us-east-1.k8s.appianci.net
    http:
      paths:
      - path: /
        backend:
          serviceName: Ballerina
          servicePort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: Ballerina
  namespace: ballerina
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: Ballerina
    spec:
      hostname: Ballerina
      imagePullSecrets:
      - name: appian-docker-registry
      containers:
      - name: Ballerina
        image: artifacts.eng.appianci.net/sandbox/Ballerina:0.1
        ports:
        - containerPort: 3001
          protocol: TCP
          name: Ballerina
